[filter_remote]
https://raw.githubusercontent.com/duyufansh2008/proxy-rules-hk/main/quantumult-x/filter/ai.list, tag=AI, enabled=true
https://raw.githubusercontent.com/duyufansh2008/proxy-rules-hk/main/quantumult-x/filter/social.list, tag=Social, enabled=true

[filter_local]
FINAL,DIRECT
