[General]
loglevel = notify
ipv6 = false
skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local
bypass-tun = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12
dns-server = 1.1.1.1, 8.8.8.8, system
internet-test-url = http://www.gstatic.com/generate_204
proxy-test-url = http://www.gstatic.com/generate_204
test-timeout = 3

[Proxy]
Proxy = socks5, 127.0.0.1, 1080

[Proxy Group]
Proxy = select, Proxy, DIRECT

[Rule]
RULE-SET,https://raw.githubusercontent.com/duyufansh2008/proxy-rules-hk/main/surge/ruleset/ai.list,Proxy
RULE-SET,https://raw.githubusercontent.com/duyufansh2008/proxy-rules-hk/main/surge/ruleset/social.list,Proxy
FINAL,DIRECT
