[Proxy]
Proxy = socks5, 127.0.0.1, 1080

[Proxy Group]
Proxy = select, Proxy, DIRECT

[Rule]
RULE-SET,https://raw.githubusercontent.com/duyufansh2008/proxy-rules-hk/main/surge/ruleset/ai.list,Proxy
RULE-SET,https://raw.githubusercontent.com/duyufansh2008/proxy-rules-hk/main/surge/ruleset/social.list,Proxy
FINAL,DIRECT
